name: barotse3

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pcraster
  - cartopy
  - rasterio
  - geopandas
  - click
  - configparser
  - numpy=1.21
  - scipy
  - gdal
  - jupyter
  - netcdf4
  - pytz
  - six
  - cftime
  - xarray
  - pyproj
  - numba
  - pyinstaller
  - setuptools_scm
  - setuptools
  - pip
  - python-dateutil
  - matplotlib
  - pcraster
  - wflow
  - pip:
    - bmi-python>=0.2.6
    # - pyviz
    #- git+https://github.com/UU-Hydro/PCR_BMI.git@migrate_to_py3
    - git+https://github.com/openearth/glofrim.git
    #- git+https://github.com/openstreams/wflow.git
